Build cleanup 2020 07 06 (#73)
* Fix lerna dependency vs. watch problem
- core package's types are now built with a "prebuild" step
- Corrects problem error TS2688: Cannot find type definition file for 'finsemble'

* Remove unused references from useFavorites

* Updated readme with information on restarting VSC's typescript server

* Remove unused webpack config in finsemble-ui

* Added license information for FEA

* Rejiggering of dependencies

* Remove unecessasry extra build-types pass

* Added @chartiq/finsemble dependency back to ui
- Typescript checks were failing without a devDependency